<?php

/**
 * @file
 * Contains perf.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function perf_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the perf module.
    case 'help.page.perf':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Performance') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function perf_theme() {
  return [
    'perf' => [
      'render element' => 'children',
    ],
  ];
}
